import { AlertCircle, ListChecks, Plus, RefreshCw, Search } from "lucide-react"
import { useDeferredValue, useMemo, useState } from "react"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Skeleton } from "@/components/ui/skeleton"
import { useAccounts } from "@/features/accounts/model/use-accounts"
import { useCategories } from "@/features/categories/model/use-categories"
import { DeleteTransactionDialog } from "@/features/transactions/components/delete-transaction-dialog"
import { TransactionFormDialog } from "@/features/transactions/components/transaction-form-dialog"
import { TransactionTable } from "@/features/transactions/components/transaction-table"
import type { Transaction, TransactionPayload, TransactionStatus, TransactionType } from "@/features/transactions/model/transaction-types"
import { useTransactions } from "@/features/transactions/model/use-transactions"
import { firstErrorMessage } from "@/lib/http/api-error"

type TypeFilter = TransactionType | "all"
export function TransactionsPage() {
  const [status, setStatus] = useState<TransactionStatus>("active"); const [type, setType] = useState<TypeFilter>("all"); const [search, setSearch] = useState(""); const deferredSearch = useDeferredValue(search.trim()); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [accountId, setAccountId] = useState("all"); const [categoryId, setCategoryId] = useState("all"); const [page, setPage] = useState(1)
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Transaction | null>(null); const [deleting, setDeleting] = useState<Transaction | null>(null)
  const filters = useMemo(() => ({ status, type: type === "all" ? undefined : type, search: deferredSearch || undefined, date_from: dateFrom || undefined, date_to: dateTo || undefined, account_id: accountId === "all" ? undefined : Number(accountId), category_id: categoryId === "all" ? undefined : Number(categoryId), page }), [accountId, categoryId, dateFrom, dateTo, deferredSearch, page, status, type])
  const { result, isLoading, error, refresh, create, update, remove, restore } = useTransactions(filters)
  const accountsState = useAccounts({ status: "all" }); const categoriesState = useCategories({ status: "all" }); const pageError = error ?? accountsState.error ?? categoriesState.error
  const changeStatus = (value: TransactionStatus) => { setStatus(value); setPage(1) }; const changeType = (value: TypeFilter) => { setType(value); setPage(1) }
  const openCreate = () => { setEditing(null); setFormOpen(true) }; const openEdit = (item: Transaction) => { setEditing(item); setFormOpen(true) }
  const save = (payload: TransactionPayload) => editing ? update(editing.id, payload) : create(payload)
  const restoreItem = async (item: Transaction) => { try { await restore(item.id); toast.success(`${item.description} was restored`) } catch (e) { toast.error(firstErrorMessage(e, "Unable to restore this transaction.")) } }
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-heading text-2xl font-semibold tracking-tight">Transactions</h2><p className="text-sm text-muted-foreground">Track income, spending, and transfers between accounts.</p></div><Button onClick={openCreate}><Plus />New transaction</Button></div>
    <div className="space-y-3 border p-3"><div className="grid gap-3 lg:grid-cols-[minmax(180px,1fr)_150px_150px_150px_auto]"><div className="relative"><Search className="pointer-events-none absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-8" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder="Search transactions" aria-label="Search transactions" /></div><Select value={type} onValueChange={(v) => changeType(v as TypeFilter)}><SelectTrigger aria-label="Filter transaction type"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All types</SelectItem><SelectItem value="expense">Expense</SelectItem><SelectItem value="income">Income</SelectItem><SelectItem value="transfer">Transfer</SelectItem></SelectContent></Select><Input type="date" value={dateFrom} onChange={(e) => { setDateFrom(e.target.value); setPage(1) }} aria-label="From date" /><Input type="date" value={dateTo} min={dateFrom} onChange={(e) => { setDateTo(e.target.value); setPage(1) }} aria-label="To date" /><div className="flex border"><Button size="sm" variant={status === "active" ? "secondary" : "ghost"} onClick={() => changeStatus("active")}>Active</Button><Button size="sm" variant={status === "deleted" ? "secondary" : "ghost"} onClick={() => changeStatus("deleted")}>Deleted</Button></div></div><div className="grid gap-3 sm:grid-cols-2"><Select value={accountId} onValueChange={(value) => { setAccountId(value); setPage(1) }}><SelectTrigger aria-label="Filter by account"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All accounts</SelectItem>{accountsState.accounts.map((account) => <SelectItem key={account.id} value={String(account.id)}>{account.name}</SelectItem>)}</SelectContent></Select><Select value={categoryId} onValueChange={(value) => { setCategoryId(value); setPage(1) }}><SelectTrigger aria-label="Filter by category"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categoriesState.categories.map((category) => <SelectItem key={category.id} value={String(category.id)}>{category.name}</SelectItem>)}</SelectContent></Select></div></div>
    {pageError && <Alert variant="destructive"><AlertCircle /><AlertTitle>Unable to load transactions</AlertTitle><AlertDescription>{pageError}</AlertDescription><Button size="sm" variant="outline" className="mt-2" onClick={() => void refresh()}><RefreshCw />Try again</Button></Alert>}
    {isLoading ? <div className="space-y-2 border p-4" aria-label="Loading transactions">{Array.from({ length: 5 }).map((_, i) => <Skeleton className="h-12" key={i} />)}</div> : result?.data.length ? <><TransactionTable transactions={result.data} onEdit={openEdit} onDelete={setDeleting} onRestore={(item) => void restoreItem(item)} /><div className="flex items-center justify-between text-sm"><span>Page {result.meta.current_page} of {result.meta.last_page} · {result.meta.total} transactions</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Previous</Button><Button variant="outline" size="sm" disabled={page >= result.meta.last_page} onClick={() => setPage((p) => p + 1)}>Next</Button></div></div></> : <div className="grid min-h-56 place-items-center border border-dashed p-8 text-center"><div><ListChecks className="mx-auto mb-3 size-8 text-muted-foreground" /><h3 className="font-heading font-semibold">{status === "deleted" ? "No deleted transactions" : "No transactions found"}</h3><p className="mt-1 text-sm text-muted-foreground">Record your first transaction to update accounts and budgets.</p>{status === "active" && <Button className="mt-4" onClick={openCreate}><Plus />Create transaction</Button>}</div></div>}
    <TransactionFormDialog open={formOpen} transaction={editing} accounts={accountsState.accounts} categories={categoriesState.categories} onOpenChange={setFormOpen} onSubmit={save} />
    <DeleteTransactionDialog transaction={deleting} onOpenChange={(open) => { if (!open) setDeleting(null) }} onConfirm={(item) => remove(item.id)} />
  </div>
}
