#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

$yiiEnvironment = getenv('YII_ENV') ?: 'dev';
$yiiDebugDefault = $yiiEnvironment === 'dev' ? '1' : '0';

defined('YII_DEBUG') or define(
    'YII_DEBUG',
    filter_var(getenv('YII_DEBUG') ?: $yiiDebugDefault, FILTER_VALIDATE_BOOLEAN)
);
defined('YII_ENV') or define('YII_ENV', $yiiEnvironment);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
